export { ModuleEntity } from './model/types/module'
export { ModuleDisplay } from './model/consts/module'
export { getModuleDetailsError, getModuleDetailsIsLoading, getModuleDetailsData } from './model/selectors/getModuleSelectors'
export { moduleDetailsActions, moduleDetailsReducer } from './model/slice/moduleDetailsSlice'
export { ModuleDetailsSchema } from './model/types/module'
export { ModuleDetails } from './ui/ModuleDetails/ModuleDetails'
